---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages for ubuntu and update cache
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest  
      update_cache: yes

